[package]
name = "raptor-asset"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
raptor-anim = { path = "../raptor-anim" }
raptor-core = { path = "../raptor-core" }
raptor-config = { path = "../raptor-config" }
raptor-gpu = { path = "../raptor-gpu" }
raptor-gfx = { path = "../raptor-gfx" }
ash = { version = "0.38", default-features = false, features = ["std", "debug"] }
raptor-render = { path = "../raptor-render" }
raptor-level = { path = "../raptor-level" }
raptor-mesh = { path = "../raptor-mesh" }
base64 = "0.22"
ktx2 = "0.4"
miniz_oxide = "0.8"
ruzstd = "0.7"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "bmp", "tga", "gif"] }
gltf = { version = "1.4", default-features = false, features = [
	"utils",
	"names",
	"extensions",
	"allow_empty_texture",
	"KHR_materials_pbrSpecularGlossiness",
	"KHR_materials_unlit",
] }
