pub const FRAMES_IN_FLIGHT: u32 = 2;
pub const DELETION_FRAME_SPACING: u32 = 3;

pub const MAX_ACTIVE_LIGHTS: u32 = 64;
pub const MAX_BONE_MATRICES: u32 = 16384;
pub const MAX_CONCURRENT_THREADS: u32 = 10;

pub const LIGHT_TILE_SIZE: u32 = 16;
pub const MAX_LIGHTS_PER_TILE: u32 = 6;
pub const MAX_SCREEN_TILES_X: u32 = 240;
pub const MAX_SCREEN_TILES_Y: u32 = 135;
pub const MAX_SCREEN_TILES: u32 = MAX_SCREEN_TILES_X * MAX_SCREEN_TILES_Y;

pub const MAX_DECALS: u32 = 512;
pub const MAX_VISIBLE_DECALS: u32 = 512;
pub const DECAL_MASK_WORDS: u32 = MAX_VISIBLE_DECALS / 32;

pub const PROBE_SH_COEFF_COUNT: u32 = 9;
pub const MAX_IRRADIANCE_PROBES: u32 = 4096;
pub const MAX_PROBE_VOLUMES: u32 = 8;
pub const PROBE_GRID_EMPTY: u16 = 0xFFFF;
pub const MAX_PROBE_GRID_POINTS: u32 = 1 << 20;
pub const PROBE_GRID_DIMS: [u32; 3] = [16, 8, 16];
pub const MIN_PROBE_GRID_DIM: u32 = 2;

pub const PROBE_DEPTH_SIZE: u32 = 16;
pub const PROBE_DEPTH_FACES: u32 = 6;
pub const PROBE_DEPTH_TEXELS_PER_FACE: u32 = PROBE_DEPTH_SIZE * PROBE_DEPTH_SIZE;
pub const PROBE_DEPTH_MOMENTS_PER_TEXEL: u32 = 2;
pub const PROBE_DEPTH_FLOAT_COUNT: u32 =
	PROBE_DEPTH_FACES * PROBE_DEPTH_TEXELS_PER_FACE * PROBE_DEPTH_MOMENTS_PER_TEXEL;
pub const PROBE_DEPTH_MAX_DISTANCE: f32 = 50.0;

pub const PROBE_ATLAS_COLUMNS: u32 = 32;
pub const PROBE_ATLAS_PROBE_WIDTH: u32 = PROBE_DEPTH_FACES * PROBE_DEPTH_SIZE;
pub const PROBE_ATLAS_ROWS: u32 = MAX_IRRADIANCE_PROBES.div_ceil(PROBE_ATLAS_COLUMNS);
pub const PROBE_ATLAS_WIDTH: u32 = PROBE_ATLAS_COLUMNS * PROBE_ATLAS_PROBE_WIDTH;
pub const PROBE_ATLAS_HEIGHT: u32 = PROBE_ATLAS_ROWS * PROBE_DEPTH_SIZE;

pub const MAX_REFLECTION_PROBES: u32 = 16;
pub const REFLECTION_PROBE_SIZE: u32 = 128;
pub const REFLECTION_PROBE_MIPS: u32 = 6;
pub const REFLECTION_PROBE_FACES: u32 = 6;

pub const DFG_LUT_SIZE: u32 = 32;

const _: () = {
	assert!(MAX_VISIBLE_DECALS.is_multiple_of(32));
	assert!(MAX_IRRADIANCE_PROBES < PROBE_GRID_EMPTY as u32);
	assert!(MAX_PROBE_GRID_POINTS.is_multiple_of(2));
	assert!(PROBE_GRID_DIMS[0] * PROBE_GRID_DIMS[1] * PROBE_GRID_DIMS[2] <= MAX_IRRADIANCE_PROBES);
	assert!(PROBE_ATLAS_WIDTH <= 4096 && PROBE_ATLAS_HEIGHT <= 4096);
	assert!(PROBE_ATLAS_COLUMNS * PROBE_ATLAS_ROWS >= MAX_IRRADIANCE_PROBES);
	assert!((REFLECTION_PROBE_SIZE >> (REFLECTION_PROBE_MIPS - 1)) >= 1);
};
