[package]
name = "raptor-ffi"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
raptor-config = { path = "../raptor-config" }
raptor-mesh = { path = "../raptor-mesh" }
raptor-shader = { path = "../raptor-shader" }

[lints]
workspace = true
