True = 1
False = 0

CObjectLayer = {
    World = 0
    Player = 1
}

CPhys = {
    Static = 0
    Dynamic = 1
}

CLight = {
    Point = 0
    Spot = 1
}


CProtoMat = {
	Gray = 0
	Orange = 1
	Blue = 2
}




// the new versions, pain in the ass typing all those capitals,
// even if this is mainly for generated config files


true = 1
false = 0

cobjectlayer = {
	world = 0
	player = 1
}

cphys = {
	static = 0
	dynamic = 1
}

clight = {
	point = 0
	spot = 1
}

cprotomat = {
	grey = 0
	orange = 1
	blue = 2
}
