/*
	Globally defined constants for use across all config files.
 */

true = 1
false = 0

cobjectlayer = {
	world = 0
	player = 1
}

cphys = {
	static = 0
	dynamic = 1
}

clight = {
	point = 0
	spot = 1
}

/*
	Bit flags

	Combine flags with OR, e.g. ($objflag.unlit | $objflag.shadowcaster)
 */

objtag = {
	none = 0
	blockout = 1
	locktransform = 2
	probevolume = 4
	reflectionprobe = 8
	bleeds = 16
	spawn = 32
}

objflag = {
	none = 0
	readytorender = 1
	physicsenabled = 2
	isinstance = 4
	shadowcaster = 8
	unlit = 16
	disableculling = 32
	notprobevisible = 64
	sharedmesh = 128
}



/*
	Old constants, keeping around for legacy config files
 */

True = 1
False = 0

cprotomat = {
	grey = 0
	orange = 1
	blue = 2
	bricks = 3
	tile = 4
}
