[package]
name = "raptor-app"
version.workspace = true
edition.workspace = true
publish.workspace = true
build = "build.rs"

[[bin]]
name = "raptor"
path = "src/main.rs"
test = false

[features]
default = ["editor"]
editor = ["dep:raptor-editor"]

[dependencies]
raptor-ffi = { path = "../raptor-ffi" }
raptor-core = { path = "../raptor-core" }
raptor-game = { path = "../raptor-game" }
raptor-script = { path = "../raptor-script" }
raptor-editor = { path = "../raptor-editor", features = ["gui"], optional = true }

[lints]
workspace = true
