[package]
name = "raptor-app"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "raptor"
path = "src/main.rs"
test = false

[features]
default = ["editor"]
editor = ["dep:raptor-editor"]

[dependencies]
raptor-engine = { path = "../raptor-engine" }
raptor-core = { path = "../raptor-core" }
raptor-game = { path = "../raptor-game" }
raptor-editor = { path = "../raptor-editor", features = ["gui"], optional = true }

[lints]
workspace = true
