image = "decals.png"
tile_size = 32
atlas_size = [ 512, 768 ]
atlas_tiles = [ 16, 24 ]
groups = {
	bulletholes = {
		tile = [ 0, 0 ]
		tiles = [ 16, 16 ]
		source_size = [ 512, 512 ]
	}
	blood_splat = {
		tile = [ 0, 16 ]
		tiles = [ 8, 8 ]
		source_size = [ 256, 256 ]
	}
}
