[workspace]
resolver = "3"
exclude = ["vendor"]
members = ["raptor-app", "raptor-core", "raptor-gpu", "raptor-gfx", "raptor-render", "raptor-brush", "raptor-config", "raptor-shader", "raptor-mesh", "raptor-math", "raptor-ffi", "raptor-anim", "raptor-level", "raptor-world", "raptor-asset", "raptor-player", "raptor-physics", "raptor-entity", "raptor-jolt", "raptor-input", "raptor-scene", "raptor-weapon", "raptor-engine", "raptor-editor", "raptor-script", "raptor-game"]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.lints.clippy]
undocumented_unsafe_blocks = "warn"

[profile.dev.package.hassle-rs]
debug-assertions = false

[patch.crates-io]
oxijolt-sys = { path = "vendor/oxijolt-sys" }
